chore: add step to show build error

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -72,7 +72,11 @@ jobs:
       - name: Install dependencies
         run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
       - name: Build with Next.js
+        id: build
         run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      - name: Show error
+        if: failure()
+        run: echo "Build failed with exit code $?"
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
